added carousel files
ElenaLadutska/Carousel pull request #1
Opened 2022-10-25 14:06 UTC by ElenaLadutska

2022-11-01 09:44 UTC, kathrynowy requested changes

2022-11-01 09:44 UTC, kathrynowy commented on index.html
> +      </div>
create imgs with js
add a variable which will tell how many img you will have

2022-11-01 09:44 UTC, kathrynowy commented on index.html
> +        <p> > </p>
do ypu need this p?

2022-11-01 09:44 UTC, kathrynowy commented on index.js
> +let startedIndex = 0;
startED?

2022-11-01 09:44 UTC, kathrynowy commented on index.js
> +}
won't they be the same?

2022-11-01 09:44 UTC, kathrynowy commented on index.js
> +    startedIndex = startedIndex + 1;
startedIndex++;

2022-11-01 09:44 UTC, kathrynowy commented on index.js
> +  startedIndex = startedIndex - 1;
.

2022-11-01 09:44 UTC, kathrynowy commented on index.js
> +});
can you reuse this function? 
just pass a param or something?

make it not via eventListener, by adding it to onclick on html

2022-11-01 09:44 UTC, kathrynowy commented on index.js
> +});
function to onClick

2022-11-01 09:52 UTC, ElenaLadutska commented on index.html
> +        <p> > </p>
yes, because I need to show > here and in the left arrow too I need <

2022-11-01 09:53 UTC, ElenaLadutska commented on index.js
> +}
yeah, they will

2022-11-01 16:44 UTC, ElenaLadutska commented on index.js
> +    startedIndex = startedIndex + 1;
fixed

2022-11-01 16:44 UTC, ElenaLadutska commented on index.js
> +let startedIndex = 0;
renamed

2022-11-01 16:44 UTC, ElenaLadutska commented on index.js
> +  startedIndex = startedIndex - 1;
fixed

2022-11-09 18:48 UTC, ElenaLadutska commented on index.js
> +});
I created 2 functions.

2022-11-09 18:48 UTC, ElenaLadutska commented on index.js
> +});
fixed

2022-11-09 19:35 UTC, ElenaLadutska commented on index.js
> +});
fixed

2023-04-11 11:18 UTC, ElenaLadutska commented on index.html
> +      </div>
fixed

2023-04-11 11:19 UTC, merged